### ISSUE TITLE
Admin page formatting is broke

### ISSUE THREAD

**Issue by mehstruslehpy** [SacStateOctobots/RowingClubWebsite#80]
Mostly just for officers and testimonials tabs. Team members is perfect so we probably just need to copy our code their to the other sections. We also now have a mystery socials tab that does nothing.

Broke Officers Tab: 
![BrokeFormatting](https://github.com/SacStateOctobots/RowingClubWebsite/assets/18666896/3892aa05-14b6-466f-9f96-1f682b8011d8)

Broke Socials Tab:
![BrokeSocials](https://github.com/SacStateOctobots/RowingClubWebsite/assets/18666896/863d1bd6-b830-4cab-ad42-fce1177ac901)
(Nothing is displayed below this in the socials tab.)

**Comment by koralreeef** [comment]
check karlbranch and pull newest admin to confirm the fix
